language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
install: pip3 install tox-travis
script:
  - tox -r
  - >
    virtualenv install_with_all_deps && 
    source ./install_with_all_deps/bin/activate && 
    pip install .[all]
